services:
  - type: web
    name: maps-scrapper
    env: go
    buildCommand: go build -tags netgo -ldflags '-s -w' -o app
    startCommand: ./app
    envVars:
      - key: GO_VERSION
        value: "1.25.5"
